version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoinits
    - wsl
    - lll
    - errchkjson
    - ireturn
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - unnamedResult
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    funlen:
      lines: 60
      statements: 60
    gocyclo:
      min-complexity: 15
    cyclop:
      max-complexity: 15
    mnd:
      ignored-numbers:
        - "10"
        - "100"
        - "1000"
        - "2"
        - "60"
        - "60.0"
        - "64"
        - "500"
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    varnamelen:
      max-distance: 5
      min-name-length: 3
      check-receiver: false
      check-return: false
      ignore-type-assert-ok: false
      ignore-map-index-ok: false
      ignore-chan-recv-ok: false
      ignore-decls:
        - wg sync.WaitGroup
        - wg *sync.WaitGroup
        - mu sync.Mutex
        - ok bool
      ignore-names:
        - i
        - w
        - r
        - b
        - c
        - m
        - n
        - tt
        - rw
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples/
      - generated\.go$
      - zz_generated\.deepcopy\.go$
      - test/
    rules:
      - linters:
          - funlen
          - dupl
          - gocognit
          - gocyclo
          - cyclop
          - errcheck
          - testableexamples
          - testpackage
          - forcetypeassert
          - gocritic
          - nlreturn
          - wsl_v5
          - varnamelen
          - unparam
          - modernize
          - gosec
          - testifylint
          - perfsprint
          - paralleltest
          - maintidx
        path: _test\.go
      - linters:
          - forbidigo
          - gocyclo
          - cyclop
          - goconst
          - funlen
          - gocognit
          - nestif
          - gocritic
          - maintidx
        path: examples/
      # Controller patterns - helper methods near reconcile logic
      - linters:
          - funcorder
        path: internal/controller/
      # Controller patterns - inline error handling in reconcile
      - linters:
          - noinlineerr
          - wrapcheck
          - gocyclo
          - cyclop
          - gochecknoglobals
          - wsl_v5
          - nlreturn
          - fatcontext
          - funlen
          - godot
          - revive
        path: internal/controller/
      # Web server uses controller-runtime client
      - linters:
          - wrapcheck
          - noctx
          - wsl_v5
          - varnamelen
          - noinlineerr
          - gocyclo
          - cyclop
        path: internal/web/
      # Templ generated files
      - linters:
          - funlen
          - gocyclo
          - cyclop
          - gocognit
          - maintidx
        path: _templ\.go$
      # Kubebuilder generated cmd/main.go
      - linters:
          - funlen
          - gocyclo
          - cyclop
          - gochecknoglobals
          - gocritic
          - mnd
          - nolintlint
          - wsl_v5
          - contextcheck
          - fatcontext
          - godox
          - noinlineerr
          - wrapcheck
        path: cmd/main\.go$
      # Kubebuilder generated API files
      - linters:
          - gochecknoglobals
          - tagliatelle
          - godot
        path: api/
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples/
      - generated\.go$
